version: "3.5"
services:

  db:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/var/lib/data
    restart: always  # if the container should restart on terminated
    environment:
      MONGO_INITDB_DATABASE: users

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
    - 8080:8080

volumes:
  data:
